### ISSUE TITLE
[TRANSLATION] Français

### ISSUE THREAD

**Issue by MrEzral** [TheKiritoPlayer20/MoreOresInONE#1]
Language: [Langage]

To translate: just replace the old names, e.g to rename the "block.moreoresinone.ruby_ore" replace "Ruby Ore" with the translation and so on.

{
  "block.moreoresinone.ruby_ore" : "Minerai de Rubis",
  "block.moreoresinone.ruby_block" : "Bloc de Rubis",
  "item.moreoresinone.ruby" : "Rubis",
  "item.moreoresinone.ruby_axe" : "Hache en Rubis",
  "item.moreoresinone.ruby_hoe" : "Houe en Rubis",
  "item.moreoresinone.ruby_pickaxe" : "Pioche en Rubis",
  "item.moreoresinone.ruby_shovel" : "Pelle en Rubis",
  "item.moreoresinone.ruby_sword" : "Épée en Rubis",
  "item.moreoresinone.ruby_sickle" : "Faucille en Rubis",
  "item.moreoresinone.ruby_helmet" : "Casque en Rubis",
  "item.moreoresinone.ruby_chestplate" : "Plastron en Rubis",
  "item.moreoresinone.ruby_leggings" : "Jambières en Rubis",
  "item.moreoresinone.ruby_boots" : "Bottes en Rubis",
  "block.moreoresinone.sapphire_ore" : "Minerai de Saphir",
  "block.moreoresinone.sapphire_block" : "Bloc de Saphir",
  "item.moreoresinone.sapphire" : "Saphir",
  "item.moreoresinone.sapphire_axe" : "Hache en Saphir",
  "item.moreoresinone.sapphire_hoe" : "Houe en Saphir",
  "item.moreoresinone.sapphire_pickaxe" : "Pioche en Saphir",
  "item.moreoresinone.sapphire_shovel" : "Pelle en Saphir",
  "item.moreoresinone.sapphire_sword" : "Épée en Saphir",
  "item.moreoresinone.sapphire_sickle" : "Faucille en Saphir",
  "item.moreoresinone.sapphire_helmet" : "Casque en Saphir",
  "item.moreoresinone.sapphire_chestplate" : "Plastron en Saphir",
  "item.moreoresinone.sapphire_leggings" : "Jambières en Saphir",
  "item.moreoresinone.sapphire_boots" : "Bottes en Saphir",
  "block.moreoresinone.topaz_ore" : "Minerai de Topaze",
  "block.moreoresinone.topaz_block" : "Bloc de Topaze",
  "item.moreoresinone.topaz" : "Topaze",
  "item.moreoresinone.topaz_axe" : "Hache en Topaze",
  "item.moreoresinone.topaz_hoe" : "Houe en Topaze",
  "item.moreoresinone.topaz_pickaxe" : "Pioche en Topaze",
  "item.moreoresinone.topaz_shovel" : "Pelle en Topaze",
  "item.moreoresinone.topaz_sword" : "Épée en Topaze",
  "item.moreoresinone.topaz_sickle" : "Faucille en Topaze",
  "item.moreoresinone.topaz_helmet" : "Casque en Topaze",
  "item.moreoresinone.topaz_chestplate" : "Plastron en Topaze",
  "item.moreoresinone.topaz_leggings" : "Jambières en Topaze",
  "item.moreoresinone.topaz_boots" : "Bottes en Topaze",
  "block.moreoresinone.amethyst_ore" : "Minerai d'Améthyste",
  "block.moreoresinone.amethyst_block" : "Bloc d'Améthyste",
  "item.moreoresinone.amethyst" : "Améthyste",
  "item.moreoresinone.amethyst_axe" : "Hache en Améthyste",
  "item.moreoresinone.amethyst_hoe" : "Houe en Améthyste",
  "item.moreoresinone.amethyst_pickaxe" : "¨Pioche en Améthyste",
  "item.moreoresinone.amethyst_shovel" : "Pelle en Améthyste",
  "item.moreoresinone.amethyst_sword" : "Épée en Améthyste",
  "item.moreoresinone.amethyst_sickle" : "Faucille en Améthyste",
  "item.moreoresinone.amethyst_helmet" : "Casque en Améthyste",
  "item.moreoresinone.amethyst_chestplate" : "Plastron en Améthyste",
  "item.moreoresinone.amethyst_leggings" : "Jambières en Améthyste",
  "item.moreoresinone.amethyst_boots" : "Bottes en Améthyste",
  "itemGroup.moi_overworld" : "MOI Overworld",
  "itemGroup.moi_nether" : "MOI Nether",
  "itemGroup.moi_end" : "MOI End",
  "advancements.moreoresinone.root.title": "More Ores in ONE",
  "advancements.moreoresinone.root.description": "The More Ores est dans l'Overworld, Nether et l'End.",
  "advancements.moreoresinone.find_ruby.title": "Trouvez le minerai de Rubis",
  "advancements.moreoresinone.find_ruby.description": "Trouvez et minez le Rubis.(Se trouve dans les biomes chauds)",
  "advancements.moreoresinone.ruby_tools.title": "Outils en Rubis",
  "advancements.moreoresinone.ruby_tools.description": "Fabriquez n'importe quel outil en Rubis.",
  "advancements.moreoresinone.find_sapphire.title": "Trouvez le minerai de Saphir",
  "advancements.moreoresinone.find_sapphire.description": "Trouvez et minez du Saphir.(Se trouve dans les biomes froids.)",
  "advancements.moreoresinone.sapphire_tools.title": "Outils en Saphir",
  "advancements.moreoresinone.sapphire_tools.description": "Fabriquez n'importe quel outil en Saphire",
  "advancements.moreoresinone.find_topaz.title": "Trouvez le minerai de Topaze",
  "advancements.moreoresinone.find_topaz.description": "Trouvez et minez du Topaze.(Se trouve dans le Nether)",
  "advancements.moreoresinone.topaz_pickaxe.title": "Pioche en Topaze",
  "advancements.moreoresinone.topaz_pickaxe.description": "Fabriquez une pioche en Topaze, vous en avez besoin pour extraire l'Améthyste.",
  "advancements.moreoresinone.find_amethyst.title": "Le dernier minerai !",
  "advancements.moreoresinone.find_amethyst.description": "Trouvez et minez de l'Améthyste !(Se trouve dans l'End)",
  "advancements.moreoresinone.amethyst_tools.title": "Outils en Améthyste",
  "advancements.moreoresinone.amethyst_tools.description": "Fabriquez n'importe quel outil en Améthyste.",
  "advancements.moreoresinone.amethyst_armor.title": "Armure en Améthyste",
  "advancements.moreoresinone.amethyst_armor.description": "Fabriquez toutes les pièces d'armures en Améthyste"
}

**Comment by KiritoGames20** [comment]
Shouldnt ruby block be "Bloc de Rubis"? But overall it seems good. Thank you!

**Comment by MrEzral** [comment]
> Shouldnt ruby block be "Bloc de Rubis"? But overall it seems good. Thank you!

Indeed, little mistake, sorry ^^

**Comment by KiritoGames20** [comment]
> > Shouldnt ruby block be "Bloc de Rubis"? But overall it seems good. Thank you!
> 
> Indeed, little mistake, sorry ^^

Np. I will add your translation to More Ores in One.

**Comment by realKG20** [comment]
Hey mind translating "Experience Ore" as we will make a new ore in the next version so we dont have to release another version with the translation?

**Comment by MrEzral** [comment]
The new ore will be Experience Ore? If that's the case, it'll be "Minerai d'Expérience"

**Comment by realKG20** [comment]
Thanks. The update will be up in about 10 minutes.
