### ISSUE TITLE
mod blocks bug 

### ISSUE THREAD

**Issue by anjuo** [TheKiritoPlayer20/MoreOresInONE#10]
I was able to download the mods correctly due to the instructions given, however, when I use any tools like the Amethyst Pickaxe it works fine but if I try placing any bricks like a Block of Sapphire it will instantly disappear right after placing. Also, I tried placing some armor in the armor stand but it wont place onto them but I can still wear all the armor types.

**Comment by realKG20** [comment]
Which forge version are you using?

**Comment by anjuo** [comment]
1.15.1 forge 30.0.15

**Comment by realKG20** [comment]
Tested in forge 30.0.15 and 30.0.16. I'm sorry but I can't reproduce your bug.
