### ISSUE TITLE
[TRANSLATION] Arabic (ar_ye)

### ISSUE THREAD

**Issue by Chozen** [TheKiritoPlayer20/MoreOresInONE#11]
Language: Arabic

To translate: just replace the old names, e.g to rename the "block.moreoresinone.ruby_ore" replace "Ruby Ore" with the translation and so on.

{
  "block.moreoresinone.ruby_ore" : "ياقوت خام",
  "block.moreoresinone.ruby_block" : "مكعب من الياقوت",
  "item.moreoresinone.ruby" : "ياقوت",
  "item.moreoresinone.ruby_axe" : "فأس ياقوت",
  "item.moreoresinone.ruby_hoe" : "محراث ياقوت",
  "item.moreoresinone.ruby_pickaxe" : "معول ياقوت",
  "item.moreoresinone.ruby_shovel" : "مجرفة ياقوت",
  "item.moreoresinone.ruby_sword" : "سيف ياقوت",
  "item.moreoresinone.ruby_sickle" : "منجل ياقوت",
  "item.moreoresinone.ruby_helmet" : "خوذة ياقوتية",
  "item.moreoresinone.ruby_chestplate" : "صدرية ياقوتية",
  "item.moreoresinone.ruby_leggings" : "سروال ياقوتي",
  "item.moreoresinone.ruby_boots" : "أحذية ياقوتية",
  "block.moreoresinone.sapphire_ore" : "سافاير خام",
  "block.moreoresinone.sapphire_block" : "مكعب سافاير",
  "item.moreoresinone.sapphire" : "سافاير",
  "item.moreoresinone.sapphire_axe" : "فأس سافاير",
  "item.moreoresinone.sapphire_hoe" : "محراث سافاير",
  "item.moreoresinone.sapphire_pickaxe" : "معول سافاير",
  "item.moreoresinone.sapphire_shovel" : "مجرفة سافاير",
  "item.moreoresinone.sapphire_sword" : "سيف سافاير",
  "item.moreoresinone.sapphire_sickle" : "منجل سافاير",
  "item.moreoresinone.sapphire_helmet" : "خوذة سافاير",
  "item.moreoresinone.sapphire_chestplate" : "صدرية سافاير",
  "item.moreoresinone.sapphire_leggings" : "سروال سافاير",
  "item.moreoresinone.sapphire_boots" : "أحذية سافاير",
  "block.moreoresinone.topaz_ore" : "خام توباز",
  "block.moreoresinone.topaz_block" : "مكعب توباز",
  "item.moreoresinone.topaz" : "توباز",
  "item.moreoresinone.topaz_axe" : "فأس توباز",
  "item.moreoresinone.topaz_hoe" : "محراث توباز",
  "item.moreoresinone.topaz_pickaxe" : "معول توباز",
  "item.moreoresinone.topaz_shovel" : "مجرفة توباز",
  "item.moreoresinone.topaz_sword" : "سيف توباز",
  "item.moreoresinone.topaz_sickle" : "منجل توباز",
  "item.moreoresinone.topaz_helmet" : "خوذة توباز",
  "item.moreoresinone.topaz_chestplate" : "صدرية توباز",
  "item.moreoresinone.topaz_leggings" : "سروال توباز",
  "item.moreoresinone.topaz_boots" : "أحذية توباز",
  "block.moreoresinone.amethyst_ore" : "أميثِست خام",
  "block.moreoresinone.amethyst_block" : "مكعب أميثِست",
  "item.moreoresinone.amethyst" : "أميثِست",
  "item.moreoresinone.amethyst_axe" : "فأس أميثِست",
  "item.moreoresinone.amethyst_hoe" : "محراث أميثِست",
  "item.moreoresinone.amethyst_pickaxe" : "معول أميثِست",
  "item.moreoresinone.amethyst_shovel" : "مجرفة أميثِست",
  "item.moreoresinone.amethyst_sword" : "سيف أميثِست",
  "item.moreoresinone.amethyst_sickle" : "منجل أميثِست",
  "item.moreoresinone.amethyst_helmet" : "خوذة أميثِست",
  "item.moreoresinone.amethyst_chestplate" : "صدرية أميثِست",
  "item.moreoresinone.amethyst_leggings" : "سروال أميثِست",
  "item.moreoresinone.amethyst_boots" : "أحذية أميثِست",
  "itemGroup.moi_overworld" : "MOI Overworld",
  "itemGroup.moi_nether" : "MOI Nether",
  "itemGroup.moi_end" : "MOI End",
  "advancements.moreoresinone.root.title": "مزيد من المواد الخام",
  "advancements.moreoresinone.root.description": "المزيد من المواد الخام في الأرض و العالم السفلي (Nether) و عالم النهاية (The End)",
  "advancements.moreoresinone.find_ruby.title": "جد الياقوت الخام",
  "advancements.moreoresinone.find_ruby.description": "جد و نجّم الياقوت الخام. (يوجد في المناطق الحارّة مثل الصحراء)",
  "advancements.moreoresinone.ruby_tools.title": "أدوات ياقوتية",
  "advancements.moreoresinone.ruby_tools.description": "إصنع أي أداة ياقوتية",
  "advancements.moreoresinone.find_sapphire.title": "جد سافاير خام",
  "advancements.moreoresinone.find_sapphire.description": "جد و نجّم السافاير الخام. (يوجد في المناطق الباردة)",
  "advancements.moreoresinone.sapphire_tools.title": "أدوات من السافاير",
  "advancements.moreoresinone.sapphire_tools.description": "إصنع أي أداة من السافاير",
  "advancements.moreoresinone.find_topaz.title": "جد التوباز الخام",
  "advancements.moreoresinone.find_topaz.description": "جد و نجّم التوباز الخام. (يوجد في العالم السفلي Nether)",
  "advancements.moreoresinone.topaz_pickaxe.title": "معول توباز",
  "advancements.moreoresinone.topaz_pickaxe.description": "إصنع معول توباز،لأنك ستحتاجه لتنجيم خام الأميثِست",
  "advancements.moreoresinone.find_amethyst.title": "المادة الخام الأخيرة!",
  "advancements.moreoresinone.find_amethyst.description": "جد و نجّم خام الأميثِست (توجد في عالم النهاية The end)",
  "advancements.moreoresinone.amethyst_tools.title": "أدوات من الأميثِست",
  "advancements.moreoresinone.amethyst_tools.description": "إصنع أي أداة من الأميثِست",
  "advancements.moreoresinone.amethyst_armor.title": "دروع من الأميثِست",
  "advancements.moreoresinone.amethyst_armor.description": "إصنع جميع دروع الأميثِست"
}

**Comment by realKG20** [comment]
Thanks! Will be added in the next version.
