### ISSUE TITLE
Topaz ore doesn't work in the nether when combined with Biomes o' plenty

### ISSUE THREAD

**Issue by omscrafter** [TheKiritoPlayer20/MoreOresInONE#15]
**Describe the bug**
I made a modpack combining the More ores in ONE mod with the Biomes o' plenty mod, but when i went to the nether to get topaz it wasn't there. To confirm it just wasn't me looking properly i went into creative, made a new world, went to the nether, and removed all netherrack, lava, quartz and magmablocks, but there still wasn't any topaz ore. I did however find topaz when generating a world normally.

**Versions**
Forge version: 31.1.35 for Minecraft 1.15.2
MoreOresinOne version: 1.1 for Minecraft 1.15.2

**To Reproduce**
1. Make a modpack combining More ores in ONE with Biomes o' plenty
2. Generate new world using Biomes o' plenty template
3. Go to the nether
4. Find no topaz, because there isn't any

**Expected behavior**
I expected to find topaz ore

**Screenshots**
It wouldn't make any sense to add screenshots...

**Additional context**
I did also have other mods on, but they had nothing to do with it, since it did work when generating the world normally.

**Comment by realKG20** [comment]
Which Biomes o' Plenty version are you using?

**Comment by omscrafter** [comment]
I'm not quite sure, but probably 10.0.0.245, although it could also be 10.0.0.353. I downloaded it from 9minecraft: [http://www.9minecraft.net/biomes-o-plenty-mod/](http://www.9minecraft.net/biomes-o-plenty-mod/).

Also i've noticed it generates topaz in the standard minecraft nether biome, but those are rare in a biomes o' plenty world.

**Comment by realKG20** [comment]
Going to try to let it also generate in biomes o' plenty biomes. As you said that it still generates but only in standard minecraft biomes.

**Comment by omscrafter** [comment]
I find it that the standard minecraft nether biome mainly generates around nether fortresses.

**Comment by realKG20** [comment]
Trying to fix it in the next version. ON HOLD

**Comment by omscrafter** [comment]
1.16 is soon anyway.

**Comment by realKG20** [comment]
Yeah. I hope that Forge changes the spawning behaviour in the next version.

**Comment by omscrafter** [comment]
It might just be biomes o' plenty who's forcing their own spawning behavior of ores...
