### ISSUE TITLE
Türkçe Çeviri - Turkish Translate (tr-tr)

### ISSUE THREAD

**Issue by BayPGM2** [TheKiritoPlayer20/MoreOresInONE#16]
Language: [Turkish TR]

To translate: just replace the old names, e.g to rename the "block.moreoresinone.ruby_ore" replace "Ruby Ore" with the translation and so on.

{
  "block.moreoresinone.ruby_ore" : "Yakut Cevheri",
  "block.moreoresinone.ruby_block" : "Yakut Bloğu",
  "item.moreoresinone.ruby" : "Yakut",
  "item.moreoresinone.ruby_axe" : "Yakut Balta",
  "item.moreoresinone.ruby_hoe" : "Yakut Çapa",
  "item.moreoresinone.ruby_pickaxe" : "Yakut Kazma",
  "item.moreoresinone.ruby_shovel" : "Yakut Kürek",
  "item.moreoresinone.ruby_sword" : "Yakut Kılıç",
  "item.moreoresinone.ruby_sickle" : "Yakut Orak",
  "item.moreoresinone.ruby_helmet" : "Yakut Kask",
  "item.moreoresinone.ruby_chestplate" : "Yakut Göğüslük",
  "item.moreoresinone.ruby_leggings" : "Yakut Pantolon",
  "item.moreoresinone.ruby_boots" : "Yakut Bot",
  "block.moreoresinone.sapphire_ore" : "Safir Cevheri",
  "block.moreoresinone.sapphire_block" : "Safir Bloğu",
  "item.moreoresinone.sapphire" : "Safir",
  "item.moreoresinone.sapphire_axe" : "Safir Balta",
  "item.moreoresinone.sapphire_hoe" : "Safir Çapa",
  "item.moreoresinone.sapphire_pickaxe" : "Safir Kazma",
  "item.moreoresinone.sapphire_shovel" : "Safir Kürek",
  "item.moreoresinone.sapphire_sword" : "Safir Kılıç",
  "item.moreoresinone.sapphire_sickle" : "Safir Orak",
  "item.moreoresinone.sapphire_helmet" : "Safir Kask",
  "item.moreoresinone.sapphire_chestplate" : "Safir Göğüslük",
  "item.moreoresinone.sapphire_leggings" : "Safir Pantolon",
  "item.moreoresinone.sapphire_boots" : "Safir Bot",
  "block.moreoresinone.topaz_ore" : "Topaz Cevheri",
  "block.moreoresinone.topaz_block" : "Topaz Bloğu",
  "item.moreoresinone.topaz" : "Topaz",
  "item.moreoresinone.topaz_axe" : "Topaz Balta",
  "item.moreoresinone.topaz_hoe" : "Topaz Çapa",
  "item.moreoresinone.topaz_pickaxe" : "Topaz Kazma",
  "item.moreoresinone.topaz_shovel" : "Topaz Kürek",
  "item.moreoresinone.topaz_sword" : "Topaz Kılıç",
  "item.moreoresinone.topaz_sickle" : "Topaz Orak",
  "item.moreoresinone.topaz_helmet" : "Topaz Kask",
  "item.moreoresinone.topaz_chestplate" : "Topaz Göğüslük",
  "item.moreoresinone.topaz_leggings" : "Topaz Pantolon",
  "item.moreoresinone.topaz_boots" : "Topaz Bot",
  "block.moreoresinone.amethyst_ore" : "Ametist Cevheri",
  "block.moreoresinone.amethyst_block" : "Ametist Bloğu",
  "item.moreoresinone.amethyst" : "Ametist",
  "item.moreoresinone.amethyst_axe" : "Ametist Balta",
  "item.moreoresinone.amethyst_hoe" : "Ametist Çapa",
  "item.moreoresinone.amethyst_pickaxe" : "Ametist Kazma",
  "item.moreoresinone.amethyst_shovel" : "Ametist Kürek",
  "item.moreoresinone.amethyst_sword" : "Ametist Kılıç",
  "item.moreoresinone.amethyst_sickle" : "Ametist Orak",
  "item.moreoresinone.amethyst_helmet" : "Ametist Kask",
  "item.moreoresinone.amethyst_chestplate" : "Ametist Göğüslük",
  "item.moreoresinone.amethyst_leggings" : "Ametist Pantolon",
  "item.moreoresinone.amethyst_boots" : "Ametist Bot",
  "block.moreoresinone.overworld_exp_ore" : "Deneyim Cevheri (Dünya)",
  "block.moreoresinone.nether_exp_ore" : "Deneyim Cevheri (Nether)",
  "block.moreoresinone.end_exp_ore" : "Deneyim Cevheri (End)",
  "itemGroup.moi_overworld" : "MOI Dünya",
  "itemGroup.moi_nether" : "MOI Nether",
  "itemGroup.moi_end" : "MOI End",
  "advancements.moreoresinone.root.title": "More Ores in ONE",
  "advancements.moreoresinone.root.description": "Dünyada, Nether'da ve End'da Daha Fazla Değerli Taş Modu",
  "advancements.moreoresinone.find_ruby.title": "Kızıl Dost",
  "advancements.moreoresinone.find_ruby.description": "Yakut bul ve kaz. (Sıcak biyomlarda bulunur.)",
  "advancements.moreoresinone.ruby_tools.title": "Yakut Eşyalar!",
  "advancements.moreoresinone.ruby_tools.description": "Herhangi bir Yakut eşya üret!",
  "advancements.moreoresinone.find_sapphire.title": "Lacivert Arkadaş",
  "advancements.moreoresinone.find_sapphire.description": "Safir bul ve kaz. (Soğuk biyomlarda bulunur.)",
  "advancements.moreoresinone.sapphire_tools.title": "Safir Eşyalar!",
  "advancements.moreoresinone.sapphire_tools.description": "Herhangi bir Safir eşya üret!",
  "advancements.moreoresinone.find_topaz.title": "Sıcak Topazzz!",
  "advancements.moreoresinone.find_topaz.description": "Topaz bul ve kaz. (Nether'da bulunur.)",
  "advancements.moreoresinone.topaz_pickaxe.title": "Topaz Kazmalama!",
  "advancements.moreoresinone.topaz_pickaxe.description": "Bir Topaz Kazma üret, Ametist kazmak için ihtiyacın olacak!",
  "advancements.moreoresinone.find_amethyst.title": "(Son?) Taş!",
  "advancements.moreoresinone.find_amethyst.description": "Ametist bul ve kaz. (End'de bulunur.)",
  "advancements.moreoresinone.amethyst_tools.title": "Ametist Eşyalar!",
  "advancements.moreoresinone.amethyst_tools.description": "Herhangi bir Ametist eşya üret!",
  "advancements.moreoresinone.amethyst_armor.title": "Ametist Zırh!",
  "advancements.moreoresinone.amethyst_armor.description": "Tüm Ametist Zırh parçalarını üret!",
  "item.moreoresinone.ruby_horse_armor" : "Yakut At Zırhı",
  "item.moreoresinone.sapphire_horse_armor" : "Safir At Zırhı",
  "item.moreoresinone.topaz_horse_armor" : "Topaz At Zırhı",
  "item.moreoresinone.amethyst_horse_armor" : "Ametist At Zırhı"
}

**Comment by BayPGM2** [comment]
I hope you'll add this language in 1.16 ASAP!

**Comment by BayPGM2** [comment]
Note: If there is a new ore named "Cryortie", please tell me so I can make translation for a new ore too!

**Comment by realKG20** [comment]
Forgot to close them sry. They were already added.
