### ISSUE TITLE
Dimentional Ores Spawning in Overworld

### ISSUE THREAD

**Issue by RyanUwU** [TheKiritoPlayer20/MoreOresInONE#23]
**Issue**
Nether and End ores Spawning in overworld

**Versions**
Forge version: 36.1.31
MoreOresinOne version: MoreOresInONE-1.2_1.16.5

**To Reproduce**
Steps to reproduce the behaviour:
1. Create A new world
2. Go down to bedrock in spectator
3. Tada

**Expected behaviour**
Well, obviously, they are not meant to be there

**Screenshots**
![image](https://user-images.githubusercontent.com/79318668/129427292-221c71b6-39eb-4b84-b8c6-c86baceb9fc1.png)
![image](https://user-images.githubusercontent.com/79318668/129427712-d7e55b25-dfdc-49b3-aa0a-7889ebbcb2e8.png)

**Additional context**
To be fair i am using a variety of world generation mods and this is a rare occurrence as I've found only one of the end ores and two of the nether ones in an hour of searching.

The pack im using: https://www.curseforge.com/minecraft/modpacks/billys-branch

**Comment by realKG20** [comment]
I will take a look at it. Haven't seen it yet. Might be, that the world generation mods are not compatible.

**Comment by realKG20** [comment]
Also, can you tell me in which biome this occurs? Or is it in every biome you've tested?

**Comment by RyanUwU** [comment]
so far ive found them in mesa biomes and under the ocean but still very rarely so im unsure if its a universal issue

**Comment by realKG20** [comment]
So far I haven't found anything. Do you have the seed of the world in which you took the pictures?

**Comment by RyanUwU** [comment]
yep i have the seed
Seed: [2008950954]

**Comment by realKG20** [comment]
Did you find them direct under you when you spawned or where did you find? Coordinates would be nice

**Comment by RyanUwU** [comment]
mfw i cant find it anymore

**Comment by RyanUwU** [comment]
bingo

**Comment by RyanUwU** [comment]
![image](https://user-images.githubusercontent.com/79318668/129446218-9e8f1585-c203-425b-afd4-5c2944816238.png)

**Comment by RyanUwU** [comment]
as you can see this is absolutely huge deposit

**Comment by realKG20** [comment]
Was this screenshot still taken in the same world seed? Or did you create a new one? If so, what is the seed of this world?

**Comment by realKG20** [comment]
Also which world type did you use when creating the world?

**Comment by RyanUwU** [comment]
same seed and terraforged world type

**Comment by realKG20** [comment]
![2021-08-14_15 08 33](https://user-images.githubusercontent.com/34043946/129447343-a5c7dc1c-a1dd-4052-a154-5406c3e87de7.png)

I used the same seed as you can see in the picture and got the same position. I tested it with Biomes O' Plenty world generation and terraforged world however I haven't found them. This way I can't tell what caused it and I won't be able to fix it.
