### ISSUE TITLE
Topaz Suggestion.

### ISSUE THREAD

**Issue by blueps5controller** [TheKiritoPlayer20/MoreOresInONE#3]
Topaz Armor/Tools
Topaz Armor should have a integrated thorn effect but its basically fire aspect on the armor so if something hits you its set ablaze.
Swords should have integrated Fire Aspect (its from the nether!).

Thank You,Much Love
- Rosenhiem

**Comment by realKG20** [comment]
I like the of idea that the sword has fire aspect as a default "enchantment" for the Armor i'm gonna think about it.

**Comment by realKG20** [comment]
For right now the Sword will get its Fire Aspect "enchantment" however the Topaz Armor is still a problem with it's thorn effect, which will burn Mobs and Players which hit you. It might taken some time till a find a good solution for this.

**Comment by realKG20** [comment]
Added now in version 1.4
