### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by gettapini** [TheKiritoPlayer20/MoreOresInONE#4]
Language: Russian

To translate: just replace the old names, e.g to rename the "block.moreoresinone.ruby_ore" replace "Ruby Ore" with the translation and so on.

{
  "block.moreoresinone.ruby_ore" : "Рубиновая руда",
  "block.moreoresinone.ruby_block" : "Блок рубина",
  "item.moreoresinone.ruby" : "Рубин",
  "item.moreoresinone.ruby_axe" : "Рубиновый топор",
  "item.moreoresinone.ruby_hoe" : "Рубиновая мотыга",
  "item.moreoresinone.ruby_pickaxe" : "Рубиновая кирка",
  "item.moreoresinone.ruby_shovel" : "Рубиновая лопата",
  "item.moreoresinone.ruby_sword" : "Рубиновый меч",
  "item.moreoresinone.ruby_sickle" : "Рубиновый серп",
  "item.moreoresinone.ruby_helmet" : "Рубиновый шлем",
  "item.moreoresinone.ruby_chestplate" : "Рубиновая кираса",
  "item.moreoresinone.ruby_leggings" : "Рубиновые поножи",
  "item.moreoresinone.ruby_boots" : "Рубиновые ботинки",
  "block.moreoresinone.sapphire_ore" : "Сапфировая руда",
  "block.moreoresinone.sapphire_block" : "Блок сапфира",
  "item.moreoresinone.sapphire" : "Сапфир",
  "item.moreoresinone.sapphire_axe" : "Сапфировый топор",
  "item.moreoresinone.sapphire_hoe" : "Сапфировая мотыга",
  "item.moreoresinone.sapphire_pickaxe" : "Сапфировая кирка",
  "item.moreoresinone.sapphire_shovel" : "Сапфировая лопата",
  "item.moreoresinone.sapphire_sword" : "Сапфировый меч",
  "item.moreoresinone.sapphire_sickle" : "Сапфировый серп",
  "item.moreoresinone.sapphire_helmet" : "Сапфировый шлем",
  "item.moreoresinone.sapphire_chestplate" : "Сапфировый нагрудник",
  "item.moreoresinone.sapphire_leggings" : "Сапфировые поножи",
  "item.moreoresinone.sapphire_boots" : "Сапфировые ботинки",
  "block.moreoresinone.topaz_ore" : "Топазовая руда",
  "block.moreoresinone.topaz_block" : "Блок топаза",
  "item.moreoresinone.topaz" : "Топаз",
  "item.moreoresinone.topaz_axe" : "Топазовый топор",
  "item.moreoresinone.topaz_hoe" : "Топазовая мотыга",
  "item.moreoresinone.topaz_pickaxe" : "Топазовая кирка",
  "item.moreoresinone.topaz_shovel" : "Топазовая лопата",
  "item.moreoresinone.topaz_sword" : "Топазовый меч",
  "item.moreoresinone.topaz_sickle" : "Топазовый серп",
  "item.moreoresinone.topaz_helmet" : "Топазовый шлем",
  "item.moreoresinone.topaz_chestplate" : "Топазовый нагрудник",
  "item.moreoresinone.topaz_leggings" : "Топазовые поножи",
  "item.moreoresinone.topaz_boots" : "Топазовые ботинки",
  "block.moreoresinone.amethyst_ore" : "Аметистовая руда",
  "block.moreoresinone.amethyst_block" : "Блок аметиста",
  "item.moreoresinone.amethyst" : "Аметист",
  "item.moreoresinone.amethyst_axe" : "Аметистовый топор",
  "item.moreoresinone.amethyst_hoe" : "Аметистовая мотыга",
  "item.moreoresinone.amethyst_pickaxe" : "Аметистовая кирка",
  "item.moreoresinone.amethyst_shovel" : "Аметистовая лопата",
  "item.moreoresinone.amethyst_sword" : "Аметистовый меч",
  "item.moreoresinone.amethyst_sickle" : "Аметистовый серп",
  "item.moreoresinone.amethyst_helmet" : "Аметистовый шлем",
  "item.moreoresinone.amethyst_chestplate" : "Аметистовый нагрудник",
  "item.moreoresinone.amethyst_leggings" : "Аметистовые поножи",
  "item.moreoresinone.amethyst_boots" : "Аметистовые ботинки",
  "block.moreoresinone.overworld_exp_ore" : "Руда опыта",
  "block.moreoresinone.nether_exp_ore" : "Руда опыта",
  "block.moreoresinone.end_exp_ore" : "Руда опыта",
  "itemGroup.moi_overworld" : "MOI Верхний мир",
  "itemGroup.moi_nether" : "MOI Ад",
  "itemGroup.moi_end" : "MOI Энд",
  "advancements.moreoresinone.root.title": "More Ores in ONE",
  "advancements.moreoresinone.root.description": "Мод, который добавляет больше руд в Верхний мир, Ад и Энд.",
  "advancements.moreoresinone.find_ruby.title": "Найдите рубиновую руду",
  "advancements.moreoresinone.find_ruby.description": "Найдите и вскопайте рубиновую руду (Находится в жарких биомах).",
  "advancements.moreoresinone.ruby_tools.title": "Рубиновые инструменты",
  "advancements.moreoresinone.ruby_tools.description": "Создайте любой инструмент из рубина.",
  "advancements.moreoresinone.find_sapphire.title": "Найдите сапфировую руду",
  "advancements.moreoresinone.find_sapphire.description": "Найдите и вскопайте сапфировую руду (Находится в холодных биомах).",
  "advancements.moreoresinone.sapphire_tools.title": "Сапфировые инструменты",
  "advancements.moreoresinone.sapphire_tools.description": "Создайте любой инструмент из сапфира.",
  "advancements.moreoresinone.find_topaz.title": "Найдите топазовую руду",
  "advancements.moreoresinone.find_topaz.description": "Найдите и вскопайте топазовую руду (Находится в Аду).",
  "advancements.moreoresinone.topaz_pickaxe.title": "Топазовая кирка",
  "advancements.moreoresinone.topaz_pickaxe.description": "Создайте топазовую кирку, так она нужна вам для того, чтобы вскопать аметистовую руду.",
  "advancements.moreoresinone.find_amethyst.title": "Последняя руда!",
  "advancements.moreoresinone.find_amethyst.description": "Найдите и сломайте аметистовую руду! (Находится в Энде).",
  "advancements.moreoresinone.amethyst_tools.title": "Аметистовые инструменты",
  "advancements.moreoresinone.amethyst_tools.description": "Создайте любой инструмент из аметиста.",
  "advancements.moreoresinone.amethyst_armor.title": "Аметистовая броня",
  "advancements.moreoresinone.amethyst_armor.description": "Создайте любую часть брони из аметиста."
}

**Comment by realKG20** [comment]
Thanks! Will be added in the next version.
