### ISSUE TITLE
[TRANSLATION]Spanish

### ISSUE THREAD

**Issue by mauriciolanda4** [TheKiritoPlayer20/MoreOresInONE#5]
Language: [Spanish]
{
  "block.moreoresinone.ruby_ore" : "Mineral de Rubí",
  "block.moreoresinone.ruby_block" : "Bloque de Rubí",
  "item.moreoresinone.ruby" : "Rubí",
  "item.moreoresinone.ruby_axe" : "Hacha de rubí",
  "item.moreoresinone.ruby_hoe" : " Azadón de rubí",
  "item.moreoresinone.ruby_pickaxe" : "Pico de Rubí",
  "item.moreoresinone.ruby_shovel" : "Pala de Rubí",
  "item.moreoresinone.ruby_sword" : "Espada de Rubí",
  "item.moreoresinone.ruby_sickle" : "Hoz de Rubí",
  "item.moreoresinone.ruby_helmet" : "Casco Rubí",
  "item.moreoresinone.ruby_chestplate" : "Peto de Rubí",
  "item.moreoresinone.ruby_leggings" : "Leotardos de Rubí",
  "item.moreoresinone.ruby_boots" : "Botas de Rubí",
  "block.moreoresinone.sapphire_ore" : "Mineral de Zafiro",
  "block.moreoresinone.sapphire_block" : "Bloque de Zafiro",
  "item.moreoresinone.sapphire" : "Zafiro",
  "item.moreoresinone.sapphire_axe" : "Hacha Zafiro",
  "item.moreoresinone.sapphire_hoe" : "Azadón de Zafiro",
  "item.moreoresinone.sapphire_pickaxe" : "Pico de Zafiro",
  "item.moreoresinone.sapphire_shovel" : "Pala de Zafiro",
  "item.moreoresinone.sapphire_sword" : "Espada de Zafiro",
  "item.moreoresinone.sapphire_sickle" : "Hoz de Zafiro",
  "item.moreoresinone.sapphire_helmet" : "Casco Zafiro",
  "item.moreoresinone.sapphire_chestplate" : "Peto de Zafiro",
  "item.moreoresinone.sapphire_leggings" : "Leotardos de Zafiro",
  "item.moreoresinone.sapphire_boots" : "Botas de Zafiro",
  "block.moreoresinone.topaz_ore" : "Mineral de Topacio",
  "block.moreoresinone.topaz_block" : "Bloque de Topacio",
  "item.moreoresinone.topaz" : "Topacio",
  "item.moreoresinone.topaz_axe" : "Hacha de Topacio",
  "item.moreoresinone.topaz_hoe" : "Azadón de Topacio",
  "item.moreoresinone.topaz_pickaxe" : "Pico de Topacio",
  "item.moreoresinone.topaz_shovel" : "Pala de Topacio",
  "item.moreoresinone.topaz_sword" : "Espada de Topacio",
  "item.moreoresinone.topaz_sickle" : "Hoz de Topacio",
  "item.moreoresinone.topaz_helmet" : "Casco Topacio",
  "item.moreoresinone.topaz_chestplate" : "Peto de Topacio",
  "item.moreoresinone.topaz_leggings" : "Leotardos de Topacio",
  "item.moreoresinone.topaz_boots" : "Botas de Topacio",
  "block.moreoresinone.amethyst_ore" : "Mineral de Amatista",
  "block.moreoresinone.amethyst_block" : "Bloque de Amatista",
  "item.moreoresinone.amethyst" : "Amatista",
  "item.moreoresinone.amethyst_axe" : "Hacha Amatista",
  "item.moreoresinone.amethyst_hoe" : "Azadón de Amatista",
  "item.moreoresinone.amethyst_pickaxe" : "Pico de Amatista",
  "item.moreoresinone.amethyst_shovel" : "Pala de Amatista",
  "item.moreoresinone.amethyst_sword" : "Espada Amatista",
  "item.moreoresinone.amethyst_sickle" : "Hoz de Amatista",
  "item.moreoresinone.amethyst_helmet" : "Casco Amatista",
  "item.moreoresinone.amethyst_chestplate" : "Peto de Amatista",
  "item.moreoresinone.amethyst_leggings" : "Leotardos de Amatista",
  "item.moreoresinone.amethyst_boots" : "Botas de Amatista",
  "block.moreoresinone.overworld_exp_ore" : "Minerales de Experiencia",
  "block.moreoresinone.nether_exp_ore" : "Minerales de Experiencia",
  "block.moreoresinone.end_exp_ore" : "Minerales de Experiencia",
  "itemGroup.moi_overworld" : "MOI Supramundo",
  "itemGroup.moi_nether" : "MOI Infierno",
  "itemGroup.moi_end" : "MOI Fin",
  "advancements.moreoresinone.root.title": "Más minerales en ONE",
  "advancements.moreoresinone.root.description": "El más minerales en el Supramundo, Infierno y fin Mod.",
  "advancements.moreoresinone.find_ruby.title": "Encontrar Minerales de Rubí",
  "advancements.moreoresinone.find_ruby.description": "Encuentra y Extrae Mineral de Rubí. (Se encuentra en biomas calientes)",
  "advancements.moreoresinone.ruby_tools.title": "Herramientas de Rubí",
  "advancements.moreoresinone.ruby_tools.description": "Fabrica cualquier Herramienta de Rubí.",
  "advancements.moreoresinone.find_sapphire.title": "Encontrar Mineral de Zafiro",
  "advancements.moreoresinone.find_sapphire.description": "Encuentra y Extrae Mineral de Zafiro. (Se encuentra en biomas fríos)",
  "advancements.moreoresinone.sapphire_tools.title": "Herramientas de Zafiro",
  "advancements.moreoresinone.sapphire_tools.description": "Fabrica cualquier Herramienta de Zafiro.",
  "advancements.moreoresinone.find_topaz.title": "Encontrar Mineral de Topacio",
  "advancements.moreoresinone.find_topaz.description": "Encuentra y Extrae Mineral de Topacio. (Encontrado en el Supramundo)",
  "advancements.moreoresinone.topaz_pickaxe.title": "Pico de Topacio",
  "advancements.moreoresinone.topaz_pickaxe.description": "Crea un pico de Topacio, ya que lo necesitas para extraer Amatista.",
  "advancements.moreoresinone.find_amethyst.title": "El último mineral!",
  "advancements.moreoresinone.find_amethyst.description": "¡Encuentra y Extrae Mineral de Amatista! (Encontrado al final)",
  "advancements.moreoresinone.amethyst_tools.title": "Herramientas de Amatista",
  "advancements.moreoresinone.amethyst_tools.description": "Fabrica cualquier Herramienta de Amatista.",
  "advancements.moreoresinone.amethyst_armor.title": "Armadura de Amatista",
  "advancements.moreoresinone.amethyst_armor.description": "Fabrica todas las Piezas de Armadura de Amatista"
}

**Comment by realKG20** [comment]
Thanks. Also will be added in the next More Ores In ONE version.

**Comment by mauriciolanda4** [comment]
No problem :D
