### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by Aikini** [TheKiritoPlayer20/MoreOresInONE#6]
Language: zh_cn

To translate: just replace the old names, e.g to rename the "block.moreoresinone.ruby_ore" replace "Ruby Ore" with the translation and so on.

{
  "block.moreoresinone.ruby_ore" : "红宝石矿石",
  "block.moreoresinone.ruby_block" : "红宝石块",
  "item.moreoresinone.ruby" : "红宝石",
  "item.moreoresinone.ruby_axe" : "红宝石斧",
  "item.moreoresinone.ruby_hoe" : "红宝石锄",
  "item.moreoresinone.ruby_pickaxe" : "红宝石镐",
  "item.moreoresinone.ruby_shovel" : "红宝石锹",
  "item.moreoresinone.ruby_sword" : "红宝石剑",
  "item.moreoresinone.ruby_sickle" : "红宝石镰刀",
  "item.moreoresinone.ruby_helmet" : "红宝石头盔",
  "item.moreoresinone.ruby_chestplate" : "红宝石胸甲",
  "item.moreoresinone.ruby_leggings" : "红宝石护腿",
  "item.moreoresinone.ruby_boots" : "红宝石鞋子",
  "block.moreoresinone.sapphire_ore" : "蓝宝石矿石",
  "block.moreoresinone.sapphire_block" : "蓝宝石块",
  "item.moreoresinone.sapphire" : "蓝宝石",
  "item.moreoresinone.sapphire_axe" : "蓝宝石斧",
  "item.moreoresinone.sapphire_hoe" : "蓝宝石锄",
  "item.moreoresinone.sapphire_pickaxe" : "蓝宝石镐",
  "item.moreoresinone.sapphire_shovel" : "蓝宝石锹",
  "item.moreoresinone.sapphire_sword" : "蓝宝石剑",
  "item.moreoresinone.sapphire_sickle" : "蓝宝石镰刀",
  "item.moreoresinone.sapphire_helmet" : "蓝宝石头盔",
  "item.moreoresinone.sapphire_chestplate" : "蓝宝石胸甲",
  "item.moreoresinone.sapphire_leggings" : "蓝宝石护腿",
  "item.moreoresinone.sapphire_boots" : "蓝宝石鞋子",
  "block.moreoresinone.topaz_ore" : "托帕石矿石",
  "block.moreoresinone.topaz_block" : "托帕石块",
  "item.moreoresinone.topaz" : "托帕石",
  "item.moreoresinone.topaz_axe" : "托帕石斧",
  "item.moreoresinone.topaz_hoe" : "托帕石锄",
  "item.moreoresinone.topaz_pickaxe" : "托帕石镐",
  "item.moreoresinone.topaz_shovel" : "托帕石锹",
  "item.moreoresinone.topaz_sword" : "托帕石剑",
  "item.moreoresinone.topaz_sickle" : "托帕石镰刀",
  "item.moreoresinone.topaz_helmet" : "托帕石头盔",
  "item.moreoresinone.topaz_chestplate" : "托帕石胸甲",
  "item.moreoresinone.topaz_leggings" : "托帕石护腿",
  "item.moreoresinone.topaz_boots" : "托帕石鞋子",
  "block.moreoresinone.amethyst_ore" : "紫水晶矿石",
  "block.moreoresinone.amethyst_block" : "紫水晶块",
  "item.moreoresinone.amethyst" : "紫水晶",
  "item.moreoresinone.amethyst_axe" : "紫水晶斧",
  "item.moreoresinone.amethyst_hoe" : "紫水晶锄",
  "item.moreoresinone.amethyst_pickaxe" : "紫水晶镐",
  "item.moreoresinone.amethyst_shovel" : "紫水晶锹",
  "item.moreoresinone.amethyst_sword" : "紫水晶剑",
  "item.moreoresinone.amethyst_sickle" : "紫水晶镰刀",
  "item.moreoresinone.amethyst_helmet" : "紫水晶头盔",
  "item.moreoresinone.amethyst_chestplate" : "紫水晶胸甲",
  "item.moreoresinone.amethyst_leggings" : "紫水晶护腿",
  "item.moreoresinone.amethyst_boots" : "紫水晶鞋子",
  "block.moreoresinone.overworld_exp_ore" : "经验矿石",
  "block.moreoresinone.nether_exp_ore" : "经验矿石",
  "block.moreoresinone.end_exp_ore" : "经验矿石",
  "itemGroup.moi_overworld" : "MOI 主世界",
  "itemGroup.moi_nether" : "MOI 下界",
  "itemGroup.moi_end" : "MOI 末地",
  "advancements.moreoresinone.root.title": "更多矿石",
  "advancements.moreoresinone.root.description": "更多矿石将出现在主世界, 下界和末地的MOD.",
  "advancements.moreoresinone.find_ruby.title": "第一个红宝石矿石",
  "advancements.moreoresinone.find_ruby.description": "找到并挖掘一个红宝石矿石.(在热带群系找到)",
  "advancements.moreoresinone.ruby_tools.title": "红宝石工具",
  "advancements.moreoresinone.ruby_tools.description": "合成任意红宝石工具.",
  "advancements.moreoresinone.find_sapphire.title": "找到蓝宝石",
  "advancements.moreoresinone.find_sapphire.description": "找到并挖掘一个蓝宝石矿石.(在寒带群系找到)",
  "advancements.moreoresinone.sapphire_tools.title": "蓝宝石工具",
  "advancements.moreoresinone.sapphire_tools.description": "合成任意蓝宝石工具.",
  "advancements.moreoresinone.find_topaz.title": "找到托帕石",
  "advancements.moreoresinone.find_topaz.description": "找到并挖掘一个托帕石矿石.(在下界找到)",
  "advancements.moreoresinone.topaz_pickaxe.title": "托帕石镐",
  "advancements.moreoresinone.topaz_pickaxe.description": "合成一个托帕石镐,你需要它去挖掘紫水晶.",
  "advancements.moreoresinone.find_amethyst.title": "最后一个矿石!",
  "advancements.moreoresinone.find_amethyst.description": "找到并挖掘紫水晶矿石!(在末地找到)",
  "advancements.moreoresinone.amethyst_tools.title": "紫水晶工具",
  "advancements.moreoresinone.amethyst_tools.description": "合成任意紫水晶工具.",
  "advancements.moreoresinone.amethyst_armor.title": "紫水晶护甲",
  "advancements.moreoresinone.amethyst_armor.description": "合成所有紫水晶护甲"
}

**Comment by realKG20** [comment]
Thanks, going to update it with your translation.
