### ISSUE TITLE
[TRANSLATION] pt_BR

### ISSUE THREAD

**Issue by louiswdg** [TheKiritoPlayer20/MoreOresInONE#8]
Language: [Brazilian Portuguese]

To translate: just replace the old names, e.g to rename the "block.moreoresinone.ruby_ore" replace "Ruby Ore" with the translation and so on.

{
  "block.moreoresinone.ruby_ore" : "Minério de rubi",
  "block.moreoresinone.ruby_block" : "Bloco de rubi",
  "item.moreoresinone.ruby" : "Rubi",
  "item.moreoresinone.ruby_axe" : "Machado de rubi",
  "item.moreoresinone.ruby_hoe" : "Enxada de rubi",
  "item.moreoresinone.ruby_pickaxe" : "Picareta de rubi",
  "item.moreoresinone.ruby_shovel" : "Pá de rubi",
  "item.moreoresinone.ruby_sword" : "Espada de rubi",
  "item.moreoresinone.ruby_sickle" : "Foice de rubi",
  "item.moreoresinone.ruby_helmet" : "Capacete de rubi",
  "item.moreoresinone.ruby_chestplate" : "Peitoral de rubi",
  "item.moreoresinone.ruby_leggings" : "Calças de rubi",
  "item.moreoresinone.ruby_boots" : "Botas de rubi",
  "block.moreoresinone.sapphire_ore" : "Minério de safira",
  "block.moreoresinone.sapphire_block" : "Bloco de safira",
  "item.moreoresinone.sapphire" : "Safira",
  "item.moreoresinone.sapphire_axe" : "Machado de safira",
  "item.moreoresinone.sapphire_hoe" : "Enxada de safira",
  "item.moreoresinone.sapphire_pickaxe" : "Picareta de safira",
  "item.moreoresinone.sapphire_shovel" : "Pá de safira",
  "item.moreoresinone.sapphire_sword" : "Espada de safira",
  "item.moreoresinone.sapphire_sickle" : "Foice de safira",
  "item.moreoresinone.sapphire_helmet" : "Capacete de safira",
  "item.moreoresinone.sapphire_chestplate" : "Peitoral de safira",
  "item.moreoresinone.sapphire_leggings" : "Calças de safira",
  "item.moreoresinone.sapphire_boots" : "Botas de safira",
  "block.moreoresinone.topaz_ore" : "Minério de topázio",
  "block.moreoresinone.topaz_block" : "Bloco de topázio",
  "item.moreoresinone.topaz" : "Topázio",
  "item.moreoresinone.topaz_axe" : "Machado de topázio",
  "item.moreoresinone.topaz_hoe" : "Enxada de topázio",
  "item.moreoresinone.topaz_pickaxe" : "Picareta de topázio",
  "item.moreoresinone.topaz_shovel" : "Pá de topázio",
  "item.moreoresinone.topaz_sword" : "Espada de topázio",
  "item.moreoresinone.topaz_sickle" : "Foice de topázio",
  "item.moreoresinone.topaz_helmet" : "Capacete de topázio",
  "item.moreoresinone.topaz_chestplate" : "Peitoral de topázio",
  "item.moreoresinone.topaz_leggings" : "Calças de topázio",
  "item.moreoresinone.topaz_boots" : "Botas de topázio",
  "block.moreoresinone.amethyst_ore" : "Minério de ametista",
  "block.moreoresinone.amethyst_block" : "Bloco de ametista",
  "item.moreoresinone.amethyst" : "Ametista",
  "item.moreoresinone.amethyst_axe" : "Machado de ametista",
  "item.moreoresinone.amethyst_hoe" : "Enxada de ametista",
  "item.moreoresinone.amethyst_pickaxe" : "Picareta de ametista",
  "item.moreoresinone.amethyst_shovel" : "Pá de ametista",
  "item.moreoresinone.amethyst_sword" : "Espada de ametista",
  "item.moreoresinone.amethyst_sickle" : "Foice de ametista",
  "item.moreoresinone.amethyst_helmet" : "Capacete de ametista",
  "item.moreoresinone.amethyst_chestplate" : "Peitoral de ametista",
  "item.moreoresinone.amethyst_leggings" : "Calças de ametista",
  "item.moreoresinone.amethyst_boots" : "Botas de ametista",
  "block.moreoresinone.overworld_exp_ore" : "Minério de experiência",
  "block.moreoresinone.nether_exp_ore" : "Minério de experiência",
  "block.moreoresinone.end_exp_ore" : "Minério de experiência",
  "itemGroup.moi_overworld" : "MOI - Overworld",
  "itemGroup.moi_nether" : "MOI - Nether",
  "itemGroup.moi_end" : "MOI - End",
  "advancements.moreoresinone.root.title": "More Ores in ONE",
  "advancements.moreoresinone.root.description": "O mod de Mais Minérios no Overworld, Nether e End.",
  "advancements.moreoresinone.find_ruby.title": "Encontre rubi",
  "advancements.moreoresinone.find_ruby.description": "Encontre e minere rubi.(Encontrado em biomas quentes)",
  "advancements.moreoresinone.ruby_tools.title": "Ferramentas de rubi",
  "advancements.moreoresinone.ruby_tools.description": "Fabrique qualquer ferramenta de rubi",
  "advancements.moreoresinone.find_sapphire.title": "Encontre safira",
  "advancements.moreoresinone.find_sapphire.description": "Encontre e minere safira.(Encontrada em biomas frios)",
  "advancements.moreoresinone.sapphire_tools.title": "Ferramentas de safira",
  "advancements.moreoresinone.sapphire_tools.description": "Fabrique qualquer ferramenta de safira.",
  "advancements.moreoresinone.find_topaz.title": "Encontre topázio",
  "advancements.moreoresinone.find_topaz.description": "Encontre e minere topázio.(Encontrado no Nether)",
  "advancements.moreoresinone.topaz_pickaxe.title": "Picareta de topázio",
  "advancements.moreoresinone.topaz_pickaxe.description": "Fabrique uma picareta de topázio, já que é necessária para minerar ametista.",
  "advancements.moreoresinone.find_amethyst.title": "O minério final!",
  "advancements.moreoresinone.find_amethyst.description": "Encontre e minere ametista!(Encontrada no the End)",
  "advancements.moreoresinone.amethyst_tools.title": "Ferramentas de ametista",
  "advancements.moreoresinone.amethyst_tools.description": "Fabrique qualquer ferramenta de ametista.",
  "advancements.moreoresinone.amethyst_armor.title": "Armadura de ametista",
  "advancements.moreoresinone.amethyst_armor.description": "Fabrique uma armadura completa de ametista."
}

**Comment by realKG20** [comment]
Thank you, will be added to the next version.
