### ISSUE TITLE
[TRANSLATION]

### ISSUE THREAD

**Issue by torteLxd** [TheKiritoPlayer20/MoreOresInONE#9]
Language: Polish

To translate: just replace the old names, e.g to rename the "block.moreoresinone.ruby_ore" replace "Ruby Ore" with the translation and so on.

{
  "block.moreoresinone.ruby_ore" : "Ruda Rubinu",
  "block.moreoresinone.ruby_block" : "Blok Rubinu",
  "item.moreoresinone.ruby" : "Rubin",
  "item.moreoresinone.ruby_axe" : "Rubinowa Siekiera",
 "item.moreoresinone.ruby_hoe" : "Rubinowa Motyka",
  "item.moreoresinone.ruby_pickaxe" : "Rubinowy Kilof",
  "item.moreoresinone.ruby_shovel" : "Rubinowa Łopata",
  "item.moreoresinone.ruby_sword" : "Rubinowy Miecz",
  "item.moreoresinone.ruby_sickle" : "Rubinowy Sierp",
  "item.moreoresinone.ruby_helmet" : "Rubinowy Hełm",
  "item.moreoresinone.ruby_chestplate" : "Rubinowy Napierśnik",
  "item.moreoresinone.ruby_leggings" : "Rubinowe Nogawice  ",
  "item.moreoresinone.ruby_boots" : "Rubinowe Buty",
  "block.moreoresinone.sapphire_ore" : "Ruda Szafiru",
  "block.moreoresinone.sapphire_block" : "Blok Szafiru",
  "item.moreoresinone.sapphire" : "Szafir",
  "item.moreoresinone.sapphire_axe" : "Szafirowa Siekiera",
  "item.moreoresinone.sapphire_hoe" : "Szafirowa Motyka",
  "item.moreoresinone.sapphire_pickaxe" : "Szafirowy Kilof",
  "item.moreoresinone.sapphire_shovel" : "Szafirowa Łopata",
  "item.moreoresinone.sapphire_sword" : "Szafirowy Miecz",
  "item.moreoresinone.sapphire_sickle" : "Szafirowy Sierp",
  "item.moreoresinone.sapphire_helmet" : "Szafirowy Hełm",
  "item.moreoresinone.sapphire_chestplate" : "Szafirowy Napierśnik",
  "item.moreoresinone.sapphire_leggings" : "Szafirowe Nogawice",
  "item.moreoresinone.sapphire_boots" : "Szafirowe Buty",
  "block.moreoresinone.topaz_ore" : "Ruda Topazu",
  "block.moreoresinone.topaz_block" : "Blok Topazu",
  "item.moreoresinone.topaz" : "Topaz",
  "item.moreoresinone.topaz_axe" : "Topazowa Siekiera",
  "item.moreoresinone.topaz_hoe" : "Topazowa Motyka",
  "item.moreoresinone.topaz_pickaxe" : "Topazowy Kilof",
  "item.moreoresinone.topaz_shovel" : "Topazowa Łopata",
  "item.moreoresinone.topaz_sword" : "Topazowy Miecz",
  "item.moreoresinone.topaz_sickle" : "Topazowy Sierp",
  "item.moreoresinone.topaz_helmet" : "Topazowy Hełm",
  "item.moreoresinone.topaz_chestplate" : "Topazowy Napierśnik",
  "item.moreoresinone.topaz_leggings" : "Topazowe Nogawice",
  "item.moreoresinone.topaz_boots" : "Topazowe Buty",
  "block.moreoresinone.amethyst_ore" : "Ruda Ametystu",
  "block.moreoresinone.amethyst_block" : "Blok Amerystu",
  "item.moreoresinone.amethyst" : "Ametyst",
  "item.moreoresinone.amethyst_axe" : "Ametystowa Siekiera",
  "item.moreoresinone.amethyst_hoe" : "Ametystowa Motyka",
  "item.moreoresinone.amethyst_pickaxe" : "Ametystowy Kilof",
  "item.moreoresinone.amethyst_shovel" : "Ametystystowa Łopata",
  "item.moreoresinone.amethyst_sword" : "Ametystowy Miecz",
  "item.moreoresinone.amethyst_sickle" : "Ametystowy Sierp",
  "item.moreoresinone.amethyst_helmet" : "Ametystowy Hełm",
  "item.moreoresinone.amethyst_chestplate" : "Ametystowy Napierśnik",
  "item.moreoresinone.amethyst_leggings" : "Ametystowe Nogawice",
  "item.moreoresinone.amethyst_boots" : "Ametystowe Buty",
  "block.moreoresinone.overworld_exp_ore" : "Ruda Doświadczenia",
  "block.moreoresinone.nether_exp_ore" : "Ruda Doświadczenia",
  "block.moreoresinone.end_exp_ore" : "Ruda Doświadczenia",
  "itemGroup.moi_overworld" : "MOI Świat",
  "itemGroup.moi_nether" : "MOI Piekło",
  "itemGroup.moi_end" : "MOI Kres",
  "advancements.moreoresinone.root.title": "Więcej Rud w Jednym",
  "advancements.moreoresinone.root.description": "Więcej Rud na świece, w Piekle i w Kresie.",
  "advancements.moreoresinone.find_ruby.title": "Znajdż Rude Rubinu",
  "advancements.moreoresinone.find_ruby.description": "Znajdź i Wykop Rude Rubinu.(Szykaj w Ciepłych Biomach)",
  "advancements.moreoresinone.ruby_tools.title": "Rubinowe Narzędzia",
  "advancements.moreoresinone.ruby_tools.description": "Stwórz Rubinowe Narzędzie.",
  "advancements.moreoresinone.find_sapphire.title": "Znajdź Rudę Szafiru",
  "advancements.moreoresinone.find_sapphire.description": "Znajdź i Wykop Rudę Szafiru.(Szukaj w Zimnych Biomach)",
  "advancements.moreoresinone.sapphire_tools.title": "Szafirowe Narzędzia",
  "advancements.moreoresinone.sapphire_tools.description": "Stwórz Szafirowe Narzędzie.",
  "advancements.moreoresinone.find_topaz.title": "Znajdź Rudę Topazu",
  "advancements.moreoresinone.find_topaz.description": "Znajdź i Wykop Rudę Topazu.(Szukają w Piekle)",
  "advancements.moreoresinone.topaz_pickaxe.title": "Topazowy Kilof",
  "advancements.moreoresinone.topaz_pickaxe.description": "Stwórz Topazowy Kilof, tak jak potrzebujesz, by wydobyć Ametyst.",
  "advancements.moreoresinone.find_amethyst.title": "Ostatnia Ruda!",
  "advancements.moreoresinone.find_amethyst.description": "Znajdź i Wykopand mine Amethyst ore!(Found in the End)",
  "advancements.moreoresinone.amethyst_tools.title": "Ametystowe Narzędzia
  "advancements.moreoresinone.amethyst_tools.description": "Stwórz Ametystowe Narzędzie.",
  "advancements.moreoresinone.amethyst_armor.title": "Ametystowa Zbroja",
  "advancements.moreoresinone.amethyst_armor.description": "Stwórz wszystkie części Ametystowe Zbroji"
}

**Comment by realKG20** [comment]
Thanks. Will be added in the 1.15 Version.
